#ifndef TREE_ERROR_TYPES_H_
#define TREE_ERROR_TYPES_H_

typedef enum TreeVerifyResult {
    TREE_VERIFY_SUCCESS = 0,
    TREE_VERIFY_NULL_PTR,
    TREE_VERIFY_INVALID_PARENT,
    TREE_VERIFY_CYCLE_DETECTED
} TreeVerifyResult;

typedef enum {
    TREE_ERROR_NO = 0,
    TREE_ERROR_NULL_PTR,
    TREE_ERROR_ALLOCATION,
    TREE_ERROR_OPENING_FILE,
    TREE_ERROR_INVALID_NODE,
    TREE_ERROR_STRUCTURE,
    TREE_ERROR_FORMAT,
    TREE_ERROR_IO,
    TREE_ERROR_ALREADY_INITIALIZED
} TreeErrorType;


#endif // TREE_ERROR_TYPES_H_
